//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface ICDeviceInfo : NSObject <NSCopying>
{
    _Bool _upgraded;
    _Bool _upgradable;
    _Bool _isOSXDevice;
    NSString *_name;
}

+ (void)logDeviceList:(id)arg1;
- (void).cxx_destruct;
- (id)attributedStringWithAttributes:(id)arg1 asteriskColor:(struct UIColor *)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithName:(id)arg1;
- (id)initWithName:(id)arg1 upgradable:(_Bool)arg2 upgraded:(_Bool)arg3;
@property(readonly, nonatomic) _Bool isOSXDevice; // @synthesize isOSXDevice=_isOSXDevice;
- (id)loggableDescription;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (_Bool)shouldBeHidden;
@property(readonly, nonatomic) _Bool upgradable; // @synthesize upgradable=_upgradable;
@property(readonly, nonatomic) _Bool upgraded; // @synthesize upgraded=_upgraded;

@end

