//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICDrawing, ICDrawingCommand, ICDrawingContour, ICDrawingResourceHandler, ICGLContext, TSDGLDataBuffer, TSDGLFrameBuffer;

@interface ICDrawingRenderer : NSObject
{
    ICDrawingCommand *_currentCommand;
    ICGLContext *_glContext;
    TSDGLFrameBuffer *_paintFramebuffer;
    TSDGLFrameBuffer *_paintFramebufferAccumulator;
    TSDGLFrameBuffer *_originalBackFramebuffer;
    _Bool _hasRenderedIntoPaintAccumulator;
    struct __GLsync *_finishRenderingFence;
    ICDrawingResourceHandler *_resourceHandler;
    double _segmentedDistanceToNextPoint;
    unsigned int _segmentedRandomSeed;
    int _backingWidth;
    int _backingHeight;
    struct CGRect _clipRect;
    ICDrawingContour *_penContour;
    _Bool _inDrawingMode;
    struct CGSize _drawingSize;
    struct CGSize _actualSize;
    double _fromCommandSpaceScale;
    struct CGRect _contentsBounds;
    TSDGLDataBuffer *_strokeBuffer;
    CDStruct_4a3d0796 _lastPointForEraser;
    _Bool _lastPointForEraserIsValid;
    _Bool _cancelRendering;
    _Bool _solidColorBackboard;
    ICDrawing *_drawing;
    double _inputScale;
    double _eraserIndicatorAlpha;
    struct CGAffineTransform _transform;
}

- (void).cxx_destruct;
- (void)applyCommandSpaceClipRect:(struct CGRect)arg1;
@property(nonatomic) _Bool cancelRendering; // @synthesize cancelRendering=_cancelRendering;
- (void)clear;
- (_Bool)clearAndRenderCommands:(id)arg1 clippedToCommandSpaceRect:(struct CGRect)arg2 renderedBlock:(CDUnknownBlockType)arg3;
- (void)clearPaintFramebuffers;
- (struct CGRect)contentsBoundsInCommandSpace;
- (void)dealloc;
@property(nonatomic) __weak ICDrawing *drawing; // @synthesize drawing=_drawing;
- (void)drawingBeganWithCommand:(id)arg1;
- (void)drawingCancelled;
- (void)drawingEnded;
- (void)drawingRenderPoints:(const vector_d46ea067 *)arg1 fromIndex:(unsigned long long)arg2;
- (void)drawingVertexReplay:(const vector_d46ea067 *)arg1 fromIndex:(unsigned long long)arg2;
@property(nonatomic) double eraserIndicatorAlpha; // @synthesize eraserIndicatorAlpha=_eraserIndicatorAlpha;
- (void)finishRendering;
- (void)finishRenderingNoTeardownForCommand:(id)arg1;
@property(readonly, nonatomic) ICGLContext *glContext; // @synthesize glContext=_glContext;
- (id)initWithDrawingPixelSize:(struct CGSize)arg1 actualSize:(struct CGSize)arg2;
@property(nonatomic) double inputScale; // @synthesize inputScale=_inputScale;
- (struct CGImage *)newCGImage;
- (struct CGImage *)newCGImageFromGL;
- (void)printPath;
- (void)printSVGFile;
- (void)releaseDrawingFramebuffers;
- (void)releaseStrokeBuffer;
- (void)renderCommand:(id)arg1 withTransform:(struct CGAffineTransform)arg2 onPaper:(_Bool)arg3 flipped:(_Bool)arg4;
- (_Bool)renderCommands:(id)arg1 clippedToCommandSpaceRect:(struct CGRect)arg2 renderedBlock:(CDUnknownBlockType)arg3;
- (unsigned long long)renderCommands:(id)arg1 isClipped:(_Bool)arg2 renderedBlock:(CDUnknownBlockType)arg3;
- (unsigned long long)renderCommands:(id)arg1 renderedBlock:(CDUnknownBlockType)arg2;
- (void)renderEraserIndicator:(CDStruct_4a3d0796)arg1 withTransform:(struct CGAffineTransform)arg2;
- (void)renderEraserIndicatorVertices:(struct StrokeVertex *)arg1 numVertices:(unsigned long long)arg2 buffer:(id)arg3 shader:(id)arg4 withTransform:(struct CGAffineTransform)arg5;
- (double)renderEraserStroke:(const vector_d46ea067 *)arg1 command:(id)arg2 distanceToNextPoint:(double)arg3;
- (void)renderFullscreenQuadWithShader:(id)arg1 transform:(struct CGAffineTransform)arg2 flipped:(_Bool)arg3;
- (void)renderImage:(struct CGImage *)arg1;
- (void)renderImage:(struct CGImage *)arg1 clippedToCommandSpaceRect:(struct CGRect)arg2;
- (double)renderMarkerStroke:(const vector_d46ea067 *)arg1 starts:(_Bool)arg2 ends:(_Bool)arg3 command:(id)arg4 distanceToNextPoint:(double)arg5 randomSeed:(unsigned int *)arg6;
- (double)renderParticleStroke:(const vector_d46ea067 *)arg1 starts:(_Bool)arg2 ends:(_Bool)arg3 distanceToNextPoint:(double)arg4 randomSeed:(unsigned int *)arg5 alpha:(double)arg6 particleTexture:(unsigned int)arg7 spacing:(double)arg8 count:(unsigned int)arg9 size:(struct CGSize)arg10 rotateEachParticle:(_Bool)arg11;
- (double)renderPenStroke:(const vector_d46ea067 *)arg1 command:(id)arg2 distanceToNextPoint:(double)arg3;
- (double)renderPenStroke:(const vector_d46ea067 *)arg1 distanceToNextPoint:(double)arg2 alpha:(double)arg3;
- (double)renderPencilStroke:(const vector_d46ea067 *)arg1 command:(id)arg2 distanceToNextPoint:(double)arg3 randomSeed:(unsigned int *)arg4;
- (double)renderStroke:(struct Contour *)arg1 starts:(_Bool)arg2 ends:(_Bool)arg3 command:(id)arg4 distanceToNextPoint:(double)arg5 randomSeed:(unsigned int *)arg6;
- (void)renderStrokeVertices:(struct StrokeVertex *)arg1 numVertices:(unsigned long long)arg2 buffer:(id)arg3 particleTexture:(unsigned int)arg4 shader:(id)arg5;
- (void)renderStrokeVertices:(struct StrokeVertex *)arg1 numVertices:(unsigned long long)arg2 buffer:(id)arg3 shader:(id)arg4;
- (void)renderTexture:(unsigned int)arg1 flipped:(_Bool)arg2;
- (void)renderVertices:(const vector_d46ea067 *)arg1 fromIndex:(unsigned long long)arg2;
- (void)renderWithTransform:(struct CGAffineTransform)arg1 onPaper:(_Bool)arg2 clipped:(_Bool)arg3 renderBufferSize:(struct CGSize)arg4;
- (void)resetPaintFramebufferAccumulateIfNeeded;
@property(nonatomic) _Bool solidColorBackboard; // @synthesize solidColorBackboard=_solidColorBackboard;
@property(nonatomic) struct CGAffineTransform transform; // @synthesize transform=_transform;
- (void)setViewport;
- (void)setupDrawingFramebuffersIfNecessary;
- (void)setupOpenGL;
- (void)setupStrokeBufferIfNecessary;

@end

