//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class ICDrawingViewController;

@interface ICDrawingScrollView : UIScrollView
{
    ICDrawingViewController *_drawingViewController;
}

- (void).cxx_destruct;
- (id)_accessibilityScrollStatus;
@property(nonatomic) __weak ICDrawingViewController *drawingViewController; // @synthesize drawingViewController=_drawingViewController;

@end

