//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICDrawing, ICDrawingInputController, ICDrawingRendererController, ICDrawingView, NSMutableOrderedSet, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>;

@interface ICDrawingController : NSObject
{
    _Bool _liveDrawing;
    unsigned long long _liveInteraction;
    ICDrawingView *_drawingView;
    NSObject<OS_dispatch_queue> *_previewQueue;
    _Bool _previewsSuspended;
    long long _drawingOrientation;
    _Bool _cachedImageValid;
    struct CGImage *_cachedImage;
    _Bool _imageNeedsSave;
    NSMutableOrderedSet *_renderedCommands;
    ICDrawingRendererController *_rendererController;
    ICDrawing *_drawing;
    NSObject<OS_dispatch_semaphore> *_drawingSemaphore;
    NSObject<OS_dispatch_semaphore> *_interactSemaphore;
    NSObject<OS_dispatch_queue> *_interactQueue;
}

- (void).cxx_destruct;
- (struct CGImage *)CGImage;
- (void)addNewRenderedCommand:(id)arg1;
- (struct CGImage *)cachedImage;
- (void)claimForLiveDrawingInView:(id)arg1;
- (void)clearCachedImage;
- (void)dealloc;
- (void)didEndLiveInteraction;
- (void)didRenderCommands:(id)arg1;
- (void)didStartLiveInteraction;
@property(retain, nonatomic) ICDrawing *drawing; // @synthesize drawing=_drawing;
- (void)drawingChanged;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *drawingSemaphore; // @synthesize drawingSemaphore=_drawingSemaphore;
- (id)image;
@property(nonatomic) _Bool imageNeedsSave; // @synthesize imageNeedsSave=_imageNeedsSave;
- (id)init;
@property(readonly, nonatomic) ICDrawingInputController *inputController;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *interactQueue; // @synthesize interactQueue=_interactQueue;
- (void)interactRenderCommands:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)interactRenderImage:(struct CGImage *)arg1 forRenderedCommands:(id)arg2 thenRenderCommands:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)interactRenderImage:(struct CGImage *)arg1 forRenderedCommands:(id)arg2 thenRenderCommands:(id)arg3 inCommandSpaceClipRect:(struct CGRect)arg4 completion:(CDUnknownBlockType)arg5;
- (void)interactRestoreValidStateCompletion:(CDUnknownBlockType)arg1;
- (void)interactSaveImage;
- (void)interactSaveImageWithState:(long long)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *interactSemaphore; // @synthesize interactSemaphore=_interactSemaphore;
- (void)interactUpdateDrawing;
- (void)interactUpdateOrientation:(long long)arg1;
- (void)loadInitialDrawingData:(id)arg1 withImage:(struct UIImage *)arg2 completion:(CDUnknownBlockType)arg3;
- (void)performAsyncInteractBlock:(CDUnknownBlockType)arg1;
- (void)releaseClaimForLiveDrawingInView:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)renderAllInCommandSpaceRect:(struct CGRect)arg1 completion:(CDUnknownBlockType)arg2;
- (void)renderCommands:(id)arg1 clippedToCommandSpaceRect:(struct CGRect)arg2 completion:(CDUnknownBlockType)arg3;
- (void)renderCommands:(id)arg1 renderIntermediateSteps:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)renderImage:(struct UIImage *)arg1;
- (void)renderPreviewDrawing:(id)arg1 initialDrawingData:(id)arg2 withImage:(struct UIImage *)arg3 completion:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) NSMutableOrderedSet *renderedCommands; // @synthesize renderedCommands=_renderedCommands;
@property(retain, nonatomic) ICDrawingRendererController *rendererController; // @synthesize rendererController=_rendererController;
- (void)resumeDrawing;
- (void)setCachedImage:(struct CGImage *)arg1;
- (void)setDrawing:(id)arg1 initialDrawingData:(id)arg2 withImage:(struct UIImage *)arg3 loadedImage:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;
- (void)sortRenderedCommands;
- (void)suspendDrawing;
- (void)updateDrawing:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

