//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSManagedObjectID, NSMutableDictionary;

@interface ICImportLegacyAccountOperation : NSOperation
{
    _Bool _randomizeImportOrder;
    _Bool _copyingPrimaryAccount;
    _Bool _renameFolders;
    NSManagedObjectID *_legacyAccountObjectID;
    NSManagedObjectID *_destinationAccountObjectID;
    NSMutableDictionary *_legacyNoteIntegerIdToNoteIdentifierDict;
}

+ (void)ensurePermanentObjectIDForObject:(id)arg1;
+ (unsigned long long)noteMigrationBatchSize;
- (void).cxx_destruct;
- (void)cancelIfAccountWasDeleted;
- (void)copyChangesForDefaultFolder;
@property(retain, nonatomic) NSManagedObjectID *destinationAccountObjectID; // @synthesize destinationAccountObjectID=_destinationAccountObjectID;
- (id)existingImportedNoteForLegacyNote:(id)arg1 withContentHash:(id)arg2 identifier:(id)arg3 context:(id)arg4;
- (id)hashFromAttributedString:(id)arg1;
- (long long)importChoiceForLegacyNote:(id)arg1 withContentHash:(id)arg2 identifier:(id)arg3 existingImportedNote:(id)arg4 destinationAccount:(id)arg5;
- (void)importFolders;
- (id)importLegacyFolder:(id)arg1 toAccount:(id)arg2;
- (id)importLegacyNote:(id)arg1 deviceMigrationIdentifier:(id)arg2 toFolder:(id)arg3;
- (void)importNotes;
- (id)initWithLegacyAccount:(id)arg1 destinationAccount:(id)arg2 renameFolders:(_Bool)arg3;
@property(nonatomic, getter=isCopyingPrimaryAccount) _Bool copyingPrimaryAccount; // @synthesize copyingPrimaryAccount=_copyingPrimaryAccount;
- (_Bool)isLegacyNoteADuplicate:(id)arg1;
- (id)legacyAccountInContext:(struct NoteContext *)arg1;
@property(retain, nonatomic) NSManagedObjectID *legacyAccountObjectID; // @synthesize legacyAccountObjectID=_legacyAccountObjectID;
@property(retain, nonatomic) NSMutableDictionary *legacyNoteIntegerIdToNoteIdentifierDict; // @synthesize legacyNoteIntegerIdToNoteIdentifierDict=_legacyNoteIntegerIdToNoteIdentifierDict;
- (id)legacyNoteObjectIDsToImport;
- (void)main;
@property(nonatomic) _Bool randomizeImportOrder; // @synthesize randomizeImportOrder=_randomizeImportOrder;
@property(nonatomic) _Bool renameFolders; // @synthesize renameFolders=_renameFolders;

@end

