//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICImageTextAttachment.h"

@interface ICImageTextAttachment (UI)
- (struct CGSize)attachmentSizeForTextContainer:(id)arg1;
- (Class)attachmentViewClass;
@end

