//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICFreeTransformableAttachmentView.h"

#import "ICImageAttachmentPresentationDelegate.h"

@class CALayer, NSString, UIImage;

@interface ICImageAttachmentView : ICFreeTransformableAttachmentView <ICImageAttachmentPresentationDelegate>
{
    _Bool _shouldUpdateLayoutInImageDidLoad;
    CALayer *_imageLayer;
    CDUnknownBlockType _imageLoadingCancelBlock;
    struct CGPoint _centerOfSalience;
}

- (void).cxx_destruct;
- (void)animateImageArrival;
@property struct CGPoint centerOfSalience; // @synthesize centerOfSalience=_centerOfSalience;
- (void)dealloc;
- (void)didChangeAttachment;
- (void)didChangeMedia;
- (void)didMoveToWindow;
- (void)didScrollIntoVisibleRange;
- (void)didScrollOutOfVisibleRange;
- (void)didUpdatePreviewImages;
- (struct CGRect)frameForContent;
@property(readonly) UIImage *image;
- (id)imageContentsGravity;
- (void)imageDidLoad:(struct UIImage *)arg1 shouldFade:(_Bool)arg2;
- (struct CGRect)imageFrame;
@property(retain) CALayer *imageLayer; // @synthesize imageLayer=_imageLayer;
@property(copy, nonatomic) CDUnknownBlockType imageLoadingCancelBlock; // @synthesize imageLoadingCancelBlock=_imageLoadingCancelBlock;
- (struct CGSize)imageSize;
@property(readonly, nonatomic) _Bool isThumbnailView;
- (id)newNavigationController;
- (void)setFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool shouldUpdateLayoutInImageDidLoad; // @synthesize shouldUpdateLayoutInImageDidLoad=_shouldUpdateLayoutInImageDidLoad;
- (void)setupBorderForLayer:(id)arg1;
- (void)setupEventHandling;
- (void)setupImagePlaceholder;
- (void)setupImagePlaceholderIfNecessary;
- (void)sharedInit;
- (_Bool)supportsFreeTransformGesture;
- (void)updateCenterOfSalience;
- (void)updateImageInView:(_Bool)arg1;
- (void)updateImageSize;
- (struct UIView *)viewToPresentAttachmentFrom;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

