//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLayoutManager.h"

#import "ICTrackedAttributeDelegate.h"

@class ICTextController, NSMutableDictionary, NSTextContainer, UITextView;

@interface ICLayoutManager : NSLayoutManager <ICTrackedAttributeDelegate>
{
    _Bool _shouldManuallyRenderSeparateSubviews;
    _Bool _lineHeightIncludeParagraphSpacing;
    _Bool _needsClearRemovedAttachments;
    UITextView *_textView;
    NSMutableDictionary *_todoButtonsByTrackingUUID;
    NSMutableDictionary *_activeSupplementalViews;
    NSMutableDictionary *_hiddenSupplementalViews;
    struct CGPoint _cachedOrigin;
    struct CGSize _cachedTextContainerSize;
}

- (void).cxx_destruct;
- (void)_clearRemovedAttachments;
@property(retain, nonatomic) NSMutableDictionary *activeSupplementalViews; // @synthesize activeSupplementalViews=_activeSupplementalViews;
- (void)attachmentDidLoad:(id)arg1;
@property(nonatomic) struct CGPoint cachedOrigin; // @synthesize cachedOrigin=_cachedOrigin;
@property(nonatomic) struct CGSize cachedTextContainerSize; // @synthesize cachedTextContainerSize=_cachedTextContainerSize;
- (void)clearAllSupplementalViews;
- (void)clearAllTodos;
- (void)clearRemovedAttachmentsIfNeeded;
- (void)clearSupplementalViewForIdentifier:(id)arg1;
- (void)clearViewForTextAttachment:(id)arg1 removeFromSuperview:(_Bool)arg2;
- (void)contentOffsetFixWorkaroundFrom9_2;
- (void)contentSizeCategoryDidChange;
- (void)dealloc;
- (void)didPressTodoButton:(id)arg1;
- (void)drawBulletsForListRange:(struct _NSRange)arg1 paragraphStyle:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)drawGlyphsForGlyphRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2;
- (void)drawGlyphsForGlyphRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2 updateAttachments:(_Bool)arg3;
- (void)drawListStylesForCharacterRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2;
- (id)drawTodoViewForListRange:(struct _NSRange)arg1 paragraphStyle:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)ensureViewIsAddedForAttachment:(id)arg1 inCharacterRange:(struct _NSRange)arg2;
- (void)enumerateAttachmentViewsInRange:(struct _NSRange)arg1 usingBlock:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSMutableDictionary *hiddenSupplementalViews; // @synthesize hiddenSupplementalViews=_hiddenSupplementalViews;
- (void)hideSupplementalView:(struct UIView *)arg1 forIdentifier:(id)arg2;
- (void)icReplaceTextStorage:(id)arg1;
- (id)icTextView;
- (id)icaxTodoButtonForParagraphStyle:(id)arg1;
- (id)init;
- (void)invalidateLayoutForAttachment:(id)arg1;
- (struct CGRect)lineFragmentRectForGlyphAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
@property(nonatomic) _Bool lineHeightIncludeParagraphSpacing; // @synthesize lineHeightIncludeParagraphSpacing=_lineHeightIncludeParagraphSpacing;
- (struct CGRect)lineRectForRange:(struct _NSRange)arg1;
- (void)manuallyRenderSubviewsForCharacterRange:(struct _NSRange)arg1;
- (void)mediaDidLoad:(id)arg1;
@property(nonatomic) _Bool needsClearRemovedAttachments; // @synthesize needsClearRemovedAttachments=_needsClearRemovedAttachments;
- (void)processEditingForTextStorage:(id)arg1 edited:(unsigned long long)arg2 range:(struct _NSRange)arg3 changeInLength:(long long)arg4 invalidatedRange:(struct _NSRange)arg5;
- (struct _NSRange)rangeForAttachment:(id)arg1 withTextAttachment:(id *)arg2;
@property(nonatomic) _Bool shouldManuallyRenderSeparateSubviews; // @synthesize shouldManuallyRenderSeparateSubviews=_shouldManuallyRenderSeparateSubviews;
@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) NSMutableDictionary *todoButtonsByTrackingUUID; // @synthesize todoButtonsByTrackingUUID=_todoButtonsByTrackingUUID;
- (struct UIView *)supplementalViewForIdentifier:(id)arg1 allowHiddenViews:(_Bool)arg2;
@property(readonly, nonatomic) NSTextContainer *textContainer;
- (void)textContainerChangedGeometry:(id)arg1;
- (id)textContainerForGlyphAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
@property(readonly, nonatomic) ICTextController *textController;
- (void)textController:(id)arg1 addedTrackedAttribute:(id)arg2;
- (void)textController:(id)arg1 removedTrackedAttribute:(id)arg2;
- (void)textController:(id)arg1 updatedTrackedAttribute:(id)arg2;
- (void)textStorageDidEndEditingNotification:(id)arg1;
- (void)unhideSupplementalView:(struct UIView *)arg1 forIdentifier:(id)arg2;
- (void)updateFrameOfViewForAttachment:(id)arg1 inCharacterRange:(struct _NSRange)arg2 atPoint:(struct CGPoint)arg3;
- (void)updateSubviewsForCharacterRange:(struct _NSRange)arg1;
- (void)updateSubviewsForCharacterRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2;
- (void)updateVisibleSupplementalViews;
- (struct CGRect)usedLineRectForRange:(struct _NSRange)arg1;
- (struct UIView *)viewForTextAttachment:(id)arg1;
- (struct UIView *)viewForTextAttachmentNoCreate:(id)arg1;

@end

