//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICDeviceInfo.h"

@interface ICMinimalDeviceInfo : ICDeviceInfo
{
}

- (id)description;
- (id)init;
- (id)initWithName:(id)arg1 upgradable:(_Bool)arg2 upgraded:(_Bool)arg3;
- (id)loggableDescription;

@end

