//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSArray, UIActivityIndicatorView, UILabel;

@interface ICNotesTaskProgressViewController : UIViewController
{
    _Bool _didCancel;
    UILabel *_label;
    UIActivityIndicatorView *_activityIndicator;
    NSArray *_notes;
    CDUnknownBlockType _processNoteBlock;
    CDUnknownBlockType _finishBlock;
    unsigned long long _noteCounter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
- (void)cancel:(id)arg1;
@property(nonatomic) _Bool didCancel; // @synthesize didCancel=_didCancel;
@property(copy, nonatomic) CDUnknownBlockType finishBlock; // @synthesize finishBlock=_finishBlock;
- (id)initWithNotes:(id)arg1 processNoteBlock:(CDUnknownBlockType)arg2 finishBlock:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) unsigned long long noteCounter; // @synthesize noteCounter=_noteCounter;
@property(copy, nonatomic) NSArray *notes; // @synthesize notes=_notes;
@property(copy, nonatomic) CDUnknownBlockType processNoteBlock; // @synthesize processNoteBlock=_processNoteBlock;
- (void)processNotes;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

