//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UIButton, UIImageView, UILabel;

@interface ICNotesListSummaryView : UIView
{
    _Bool _lockItemVisible;
    long long _numberOfNotes;
    UILabel *_notesCountLabel;
    UIImageView *_lockIcon;
    UILabel *_lockLabel;
    UIView *_lockContainerView;
    NSLayoutConstraint *_lockContainerViewZeroHeightConstraint;
    NSLayoutConstraint *_lockContainerViewZeroWidthConstraint;
    UIButton *_button;
    CDUnknownBlockType _buttonHandler;
}

+ (id)summaryViewWithButtonPressedHandler:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (id)accessibilityElements;
- (void)awakeFromNib;
@property(nonatomic) __weak UIButton *button; // @synthesize button=_button;
- (void)buttonActionThatCausesAlphaChange:(id)arg1;
- (void)buttonActionThatEndsAlphaChange:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType buttonHandler; // @synthesize buttonHandler=_buttonHandler;
- (void)buttonTouchUpInside:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak UIView *lockContainerView; // @synthesize lockContainerView=_lockContainerView;
@property(nonatomic) __weak NSLayoutConstraint *lockContainerViewZeroHeightConstraint; // @synthesize lockContainerViewZeroHeightConstraint=_lockContainerViewZeroHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *lockContainerViewZeroWidthConstraint; // @synthesize lockContainerViewZeroWidthConstraint=_lockContainerViewZeroWidthConstraint;
@property(nonatomic) __weak UIImageView *lockIcon; // @synthesize lockIcon=_lockIcon;
@property(nonatomic) _Bool lockItemVisible; // @synthesize lockItemVisible=_lockItemVisible;
@property(nonatomic) __weak UILabel *lockLabel; // @synthesize lockLabel=_lockLabel;
@property(nonatomic) __weak UILabel *notesCountLabel; // @synthesize notesCountLabel=_notesCountLabel;
@property(nonatomic) long long numberOfNotes; // @synthesize numberOfNotes=_numberOfNotes;
- (void)setLockContainerVisible:(_Bool)arg1;
- (void)setLockItemVisible:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setNotesNumberLabelToNumberOfNotes:(long long)arg1;
- (_Bool)shouldGroupAccessibilityChildren;
- (void)sizeToFit;
- (void)updateforAccessibilityDarkerSystemColors;

@end

