//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, NSString, UIFont, UIImageView, UILabel;

@interface ICNoteEditorDateView : UIView
{
    _Bool _showsLockIcon;
    NSString *_text;
    UILabel *_label;
    NSLayoutConstraint *_lockContainerZeroWidthConstraint;
    UIImageView *_lockImageView;
}

+ (id)dateView;
- (void).cxx_destruct;
- (id)accessibilityElements;
- (void)awakeFromNib;
@property(readonly, nonatomic) UIFont *font;
- (_Bool)isAccessibilityElement;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
@property(nonatomic) __weak NSLayoutConstraint *lockContainerZeroWidthConstraint; // @synthesize lockContainerZeroWidthConstraint=_lockContainerZeroWidthConstraint;
@property(nonatomic) __weak UIImageView *lockImageView; // @synthesize lockImageView=_lockImageView;
- (void)setLockImage:(id)arg1;
@property(nonatomic) _Bool showsLockIcon; // @synthesize showsLockIcon=_showsLockIcon;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void)updateAccessibilityLabel;

@end

