//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNote.h"

#import "ICNoteUndoSupport.h"

@class NSString;

@interface ICNote (UndoSupport) <ICNoteUndoSupport>
- (_Bool)copyValuesToNote:(id)arg1;
- (void)undoablySetFolder:(id)arg1;
- (void)undoablySetFolder:(id)arg1 save:(_Bool)arg2;
- (void)undoablyTrashOrDelete;
- (void)undoablyTrashOrDeleteAndSave:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

