//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class ICNote, UIButton, UIImageView, UILabel;

@interface ICPasswordEntryViewController : UIViewController
{
    _Bool _isAnimatingOut;
    ICNote *_note;
    unsigned long long _intent;
    UIImageView *_lockImage;
    UILabel *_titleLabel;
    UIButton *_unlockButton;
    UIButton *_largeUnlockButton;
}

- (void).cxx_destruct;
- (void)beginAuthentication;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 note:(id)arg3 intent:(unsigned long long)arg4;
@property(nonatomic) unsigned long long intent; // @synthesize intent=_intent;
@property(nonatomic) _Bool isAnimatingOut; // @synthesize isAnimatingOut=_isAnimatingOut;
@property(nonatomic) __weak UIButton *largeUnlockButton; // @synthesize largeUnlockButton=_largeUnlockButton;
@property(nonatomic) __weak UIImageView *lockImage; // @synthesize lockImage=_lockImage;
@property(retain, nonatomic) ICNote *note; // @synthesize note=_note;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIButton *unlockButton; // @synthesize unlockButton=_unlockButton;
- (void)unlockPasswordButtonPressed:(id)arg1;
- (void)updateforAccessibilityDarkerSystemColors;
- (void)viewDidLoad;

@end

