//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

@class ICNote;

@interface ICPasswordAddOrRemovePasswordActivity : UIActivity
{
    CDUnknownBlockType _completionHandler;
    CDUnknownBlockType _willPerformActivityBlock;
    ICNote *_note;
}

+ (long long)activityCategory;
- (void).cxx_destruct;
- (void)accessibilityAnnounceAddOrRemovePasswordWithIntent:(unsigned long long)arg1 withNote:(id)arg2;
- (id)activityImage;
- (id)activityTitle;
- (id)activityType;
- (_Bool)canPerformWithActivityItems:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (id)initWithNote:(id)arg1 willPerformActivityBlock:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) ICNote *note; // @synthesize note=_note;
- (void)performActivity;
@property(copy, nonatomic) CDUnknownBlockType willPerformActivityBlock; // @synthesize willPerformActivityBlock=_willPerformActivityBlock;

@end

