//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICRecentlyDeletedUtilities.h"

@interface ICRecentlyDeletedUtilities (iOS)
+ (id)localizedDeleteNoteAlertMessage;
+ (id)localizedDeleteNoteAlertTitle;
+ (id)localizedRecoverNoteAlertMessage;
+ (id)localizedRecoverNoteAlertTitle;
+ (void)showRecentlyDeletedAlertIfNecessaryForNotes:(id)arg1 viewController:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (void)showRecentlyDeletedAlertIfNecessaryForViewController:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
@end

