//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSSearchableItemAttributeSet, ICGenerateSearchIndexStringsOperation, NSArray, NSDate, NSDictionary, NSManagedObjectContext, NSManagedObjectID, NSString;

@protocol ICSearchIndexable <NSObject>
- (NSString *)identifier;
- (_Bool)isHiddenFromSearch;
- (NSManagedObjectContext *)managedObjectContext;
- (NSDate *)modificationDate;
- (NSManagedObjectID *)objectID;
- (NSString *)objectIdentifier;
- (NSString *)searchDomainIdentifier;
- (NSArray *)searchIndexStringsOutHasAdditionalStrings:(_Bool *)arg1;
- (NSString *)searchIndexableTitleUsingContentTextIfNecessary:(NSString *)arg1;
- (_Bool)searchResultCanBeDeletedFromNoteContext;
- (unsigned long long)searchResultsSection;
- (CSSearchableItemAttributeSet *)searchableItemAttributeSet;
- (NSString *)searchableItemIdentifier;
- (_Bool)shouldUpdateIndexForChangedValues:(NSDictionary *)arg1;
- (long long)visibilityTestingType;

@optional
- (ICGenerateSearchIndexStringsOperation *)generateSearchIndexStringsOperation;
- (_Bool)ignoreInSearchIndexer;
- (void)releaseMemoryForIndexing;
@end

