//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICSearchIndexer.h"

@interface ICSearchIndexer (App)
- (id)mainContextObjectForSearchableItemIdentifier:(id)arg1;
- (id)mainContextObjectsForSearchableItems:(id)arg1;
- (void)reindexIfNecessary;
@end

