//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICTextAttachment.h"

@interface ICTextAttachment (UI)
- (struct CGSize)attachmentSizeForImageInTextContainer:(id)arg1 intrinsicImageSize:(struct CGSize)arg2;
- (double)attachmentThumbnailViewHeight;
- (struct UIView *)viewForLayoutManager:(id)arg1;
@end

